name: my_flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/cappuccino.jpg
  - assets/images/latte.jpg
  - assets/images/espresso.jpg
  - assets/images/americano.jpg
  - assets/images/raf_coffee.jpg
  - assets/images/cheesecake.jpg
  - assets/images/tiramisu.jpg
  - assets/images/croissant.jpg
  - assets/images/sandwich.jpg
  - assets/images/smoothie.jpg
  - assets/images/earl_grey.jpg
  - assets/images/green_tea.jpg
  - assets/images/mint_tea.jpg
  - assets/images/fruit_tea.jpg